name: run-CI

on:
  push:
    branches:
      - '**'

jobs:
  collect_services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v1

      - name: install monobuild
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6'
        run: |
          go get -d github.com/charypar/monobuild
          go install github.com/charypar/monobuild

      - name: set services matrix
        id: set-matrix
        run: |
          # See https://github.com/charypar/monobuild#change-detection
          if [ $GITHUB_REF == "refs/heads/main" ]; then
            # Main branch mode
            schedule=$(monobuild diff --main-branch)
          else
            # Feature branch mode
            schedule=$(monobuild diff --base-branch origin/main)
          fi
          echo $schedule
          dependencies=$(echo "$schedule" | awk 'BEGIN { FS = ":" } ; { print $1 }')
          echo $dependencies
          echo "::set-output name=matrix::{\"service\":[\"test-app\", \"second-test-app\"]}"

  build_and_push:
    needs: collect_services
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.collect_services.outputs.matrix)}}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: make service
        run: |
          cd lib/${{ matrix.service }}
          make service=${{ matrix.service }} tag=$GITHUB_SHA
